kind: ServiceAccount
apiVersion: v1
metadata:
  name: operator
  labels:
    control-plane: ssp-operator
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: operator
  namespace: kubevirt
  labels:
    control-plane: ssp-operator
spec:
  selector:
    matchLabels:
      control-plane: ssp-operator
  replicas: 1
  template:
    metadata:
      labels:
        control-plane: ssp-operator
    spec:
      serviceAccountName: ssp-operator
      containers:
      - command:
        - /manager
        args: ["--enable-leader-election", "--ready-probe-addr", ":9440"]
        env:
          - name: KVM_INFO_IMAGE
          - name: VALIDATOR_IMAGE
            value: "$VALIDATOR_IMG"
          - name: VIRT_LAUNCHER_IMAGE
          - name: NODE_LABELLER_IMAGE
          - name: CPU_PLUGIN_IMAGE
          - name: OPERATOR_VERSION
        image: controller:latest
        name: manager
        readinessProbe:
          httpGet:
            path: /readyz
            port: 9440
          initialDelaySeconds: 5
      terminationGracePeriodSeconds: 10
      resources:
        requests:
          memory: "150Mi"
          cpu: "100m"
