apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
    categories: Openshift Optional
    containerImage: REPLACE_IMAGE:TAG
    description: Deploys and controls additional KubeVirt resources
  name: ssp-operator.v0.0.0
  namespace: kubevirt
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: SSP is the Schema for the ssps API
      displayName: SSP
      kind: SSP
      name: ssps.ssp.kubevirt.io
      version: v1beta2
  description: Operator that deploys and controls additional KubeVirt resources
  displayName: ssp-operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - KubeVirt
  - Virtualization
  - Template
  - Performance
  - VirtualMachine
  - Node
  - Labels
  labels:
    alm-owner-kubevirt: ssp-operator
    operated-by: ssp-operator
  links:
  - name: KubeVirt
    url: https://kubevirt.io
  - name: Source Code
    url: https://github.com/kubevirt/ssp-operator
  maintainers:
  - email: kubevirt-dev@googlegroups.com
    name: KubeVirt project
  maturity: alpha
  provider:
    name: KubeVirt project
  selector:
    matchLabels:
      alm-owner-kubevirt: ssp-operator
      operated-by: ssp-operator
  version: 0.0.0
