# The following patch enables conversion webhook for CRD
# CRD conversion requires k8s 1.13 or later.
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: ssps.ssp.kubevirt.io
  annotations:
    service.beta.openshift.io/inject-cabundle: true
spec:
  conversion:
    strategy: Webhook
    webhookClientConfig:
      # this is "\n" used as a placeholder, otherwise it will be rejected by the apiserver for being blank,
      # but we're going to set it later using the cert-manager (or potentially a patch if not using cert-manager)
      # edit: caBundle will be populated by OpenShift, via the annotation above, no need for a placeholder.
      #caBundle: Cg==
      service:
        namespace: system
        name: webhook-service
        path: /convert
