name: Release VM Console Proxy

on:
  repository_dispatch:
    types: [release-vm-console-proxy]

jobs:
  release-vm-console-proxy:
    name: Release VM Console Proxy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        if: ${{ github.event.client_payload.release_version }} != ''
        uses: actions/checkout@v5
      - run: |
          RELEASE_VERSION=${{ github.event.client_payload.release_version }}
          OUTPUT_FILE=./data/vm-console-proxy-bundle/vm-console-proxy.yaml
          mkdir -p ./data/vm-console-proxy-bundle
          curl -L https://github.com/kubevirt/vm-console-proxy/releases/download/${RELEASE_VERSION}/vm-console-proxy.yaml > ${OUTPUT_FILE}
          sed -i "s/defaultVmConsoleProxyImageTag = .*$/defaultVmConsoleProxyImageTag = \"${RELEASE_VERSION}\"/" ./internal/operands/vm-console-proxy/defaults.go 

      - name: Create pull request
        if: ${{ github.event.client_payload.release_version }} != ''
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ github.token }}
          commit-message: "chore: update vm-console-proxy manifests to ${{ github.event.client_payload.release_version }}"
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          signoff: true
          branch: "vm-console-proxy-${{ github.event.client_payload.release_version }}"
          delete-branch: true
          title: "Update vm-console-proxy manifests to ${{ github.event.client_payload.release_version }}"
          body: |
            Update vm-console-proxy manifests to version ${{ github.event.client_payload.release_version }}

            **Release note**:
            ```release-note
            Update vm-console-proxy-bundle to ${{ github.event.client_payload.release_version }}
            ```
          draft: false
